version: "3"
services:
  code-server:
    image: .
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Saigon
      - PASSWORD=P@ssword #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=vscode.gotdns.ch #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
      - 8888:8000
      - 19969:8069
      - 19972:8072
    networks:
      vpcbr:
        ipv4_address: 172.172.0.10
    restart: unless-stopped

  vscode-pg14:
    image: postgres:14
    restart: always
    ports:
      - 41345:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: vscode
    volumes:
      - ./postgresql/pg14/data:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 172.172.0.11
    restart: unless-stopped
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.172.0.0/16
         gateway: 172.172.0.1
volumes:
  config:
  postgresql:
