version: "3"
services:
  code-server:
    image: vuna2004/code-server:gatsby-env
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Saigon
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN= #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
      - 8000:8000
    networks:
      vpcbr:
        ipv4_address: 172.172.0.10
    restart: unless-stopped

volumes:
  config:
